### PR TITLE
2019-12-11 update

### PR DESCRIPTION
**Pull request by jialuw**

### CODE REVIEW

**Comment by yangjl** [comment]
thank you Jialu!

**Comment by yangjl** [comment]
Jialu, the md file should be put in the `content/post/` folder, the same as others. Plus, the field name should not have a blank. I have made the above edits, just so you know.

**Comment by yangjl** [comment]
Just found that your title lacking one of the ", which cause the website to roll back to early dates

**Comment by jialuw** [comment]
Sorry for the bugs and thanks for your careful revising!

Have a good day!

**Pull request merged**
